### PR TITLE
Jam.py deployment on PythonAnywhere article added. Jampy.md

### PR DESCRIPTION
**Pull request by jam-py**
Regarding your conversation with Dean Babic on 23rd of January, please add this on help pages. 

Kind Regards,
Andrew Yushev

### CODE REVIEW

**Comment by millenniumhand** [comment]
Great! Thanks

**Comment by gpjt** [comment]
@jam-py that's live on our help pages now at https://help.pythonanywhere.com/pages/jampy

Do you have a Twitter you'd like us to @ on our tweet about it?

**Comment by jam-py** [comment]
Thank you Giles,
it would be great to use twitter account https://twitter.com/jampy_framework

Much appreciated!

Kind Regards,
Adrew Yushev

**Comment by gpjt** [comment]
Thanks -- tweet sent out :-)

**Pull request merged**
