### PR TITLE
Mention certificate file designed for Nginx

### PR DESCRIPTION
**Pull request by vinyldarkscratch**
When I was playing around with SSL certificates, I accidentally opened the "Nginx Server" ZIP that was included in my certificates from WoSign (when they still offered free certificates) and StartSSL.  I was building my own certificate chain from the "Other Server" ZIP, which caused a few issues due to inexperience.  I think it would be helpful to mention that it should be an Nginx-specific file, but of course that's just me!

### CODE REVIEW

**Comment by gpjt** [comment]
Thanks for the suggestion!  I'm a bit confused, though -- what was the difference between the "nginx server" ZIP and the "Other server" one?

The certificates we use are a pretty standard format, it's not an nginx-specific thing.

**Comment by vinyldarkscratch** [comment]
Hey @gpjt, at least on WoSign and StartSSL, the ones dedicated for Nginx servers are specifically the certificate bundle, whereas the ones for other servers are specifically each certificate separately.  The ones for Apache seem to be the root and intermediate together in one file, the domain in the other, and IIS just the intermediate and domain in separate files:

screen shot 2016-11-14 at 13 05 28

**Comment by vinyldarkscratch** [comment]
Closing this pull request since this is mostly talking about WoSign and StartSSL/StartCom, which...well, [I don't really need to say more about them](https://security.googleblog.com/2016/10/distrusting-wosign-and-startcom.html), do I?

**Comment by hjwp** [comment]
indeed not! LetsEncrypt is a nice free alternative.   our instructions here: http://help.pythonanywhere.com/pages/LetsEncrypt

thanks anyway for the contribution!

**Pull request closed without merging**
