### PR TITLE
Update MySQLBackupRestore.md

### PR DESCRIPTION
**Pull request by kdwarn**
Instructions for scheduling the backup.

### CODE REVIEW

**Comment by hjwp** [comment]
I see you've got some instructions about editing *~/.my.cnf* -- in theory, we already write that file when the user sets their password.  Have you seen problems with it?

**Comment by hjwp** [comment]
Thanks so much for the PR btw!

**Comment by hjwp** [comment]
Actually, presumably, if .my.cnf exists, then the user doesn't need to manually enter their password during the mysqldump either?  I think I can probably simplify these instructions quite a bit...

**Comment by kdwarn** [comment]
You're welcome! Glad to contribute. Regarding editing ~/.my.cnf - no problems for me. My script has now run successfully 3/3 times.

**Comment by hjwp** [comment]
here we go!  what do you think? http://help.pythonanywhere.com/pages/MySQLBackupRestore

**Comment by kdwarn** [comment]
Looks good to me!

**Pull request merged**
